# Generated by Django 5.0.6 on 2024-07-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
