# Generated by Django 5.0.6 on 2024-07-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_product_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Various', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
