# Generated by Django 5.0.8 on 2024-08-08 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autobuy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
