# Generated by Django 5.0.6 on 2024-07-18 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0004_alter_pricehistory_options_remove_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('quality', 'Quality Issue'), ('pricing', 'Pricing Issue'), ('delivery', 'Delivery Problem'), ('description', 'Incorrect Description'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tracker.product')),
            ],
        ),
    ]
