# Generated by Django 5.0.6 on 2024-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('quality', 'Quality Issue'), ('pricing', 'Pricing Issue'), ('delivery', 'Delivery Problem'), ('description', 'Incorrect Description'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
