# Generated by Django 5.0.6 on 2024-07-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tracker', '0004_alter_pricehistory_options_remove_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='shoe',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.product'),
        ),
    ]
